### PR TITLE
Remove map-iteration.ql

### PR DESCRIPTION
**Pull request by peterbourgon**
Map iteration is indeed nondeterministic, but code cannot actually rely on any specific sequence of keys, as modern versions of Go randomize key order with every call to `range`. More practically, this rule seems to be violated on ~every PR submitted to cosmos/cosmos-sdk, and is subsequently ignored: all noise, no signal.

### CODE REVIEW

**Comment by peterbourgon** [comment]
Do I need to do anything to update `qlpack.lock.yml`?

**Comment by tomtau** [comment]
@peterbourgon it's still worth being notified about it.
If the problem is the noise-signal ratio, there are other ways to address it:
1. degrade the severity to "recommendation" (instead of warning), so it won't spam the security display
2. restrict the query to e.g. check that the iteration is followed by sorting (e.g. as done in this done in this gosec fork: https://github.com/informalsystems/gosec/tree/master/rules/sdk#non-deterministic-map-iteration )

if none of these work for you, then I suggest just removing it from the default query suite instead of deleting the query

**Comment by peterbourgon** [comment]
> if none of these work for you, then I suggest just removing it from the default query suite instead of deleting the query

Great! The Cosmos SDK invokes this CodeQL repo [as such](https://github.com/cosmos/cosmos-sdk/blob/master/.github/workflows/codeql-analysis.yml)

```yaml
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'go'
        queries: crypto-com/cosmos-sdk-codeql@main,security-and-quality
```

How would we drop this query in that invocation? Manually specify the others?

**Comment by tomtau** [comment]
@peterbourgon https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#working-with-custom-configuration-files
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-additional-queries

> You specify additional queries in a queries array. Each element of the array contains a uses parameter with a value that identifies a single query file, a directory containing query files, or a query suite definition file.

Yes, I guess either list the ones to be used... one more alternative way would be to put the map iteration into a separate query suite or a directory (e.g. "unstable"), and then just specify to use the "src" directory

**Comment by tomtau** [comment]
@peterbourgon I added additional refinements on the query: https://github.com/crypto-com/cosmos-sdk-codeql/commit/44f177196d827ae0d7bc52f00b10823dcd42357e#diff-ec072f925706d0ef0658aca85d0fa1c21723537fab9a189268063b096051df06

There are still false positives, so either this could be degraded from a warning if it is too annoying or add more refinements to it (e.g. only consider iterations within ABCI consensus-related methods or that are writing out something used in ABCI consensus-related methods).
Alternatively, if the query becomes too complex (and there's perhaps a risk of false negatives), there could be a code convention to hint that the particular iteration should be ignored by the query, e.g. a code comment on a preceding line `// SAFE: <explanation why it's ok to have a non-deterministic iteration>`.

**Comment by tomtau** [comment]
@peterbourgon https://github.com/crypto-com/cosmos-sdk-codeql#false-positives

**Pull request closed without merging**
